CI:15workflows수정

diff --git a/.github/workflows/cd-develop.yml b/.github/workflows/cd-develop.yml
--- a/.github/workflows/cd-develop.yml
+++ b/.github/workflows/cd-develop.yml
@@ -1,77 +1,115 @@
-name: CD - Dev
+name: CI/CD
 
 on:
-  workflow_dispatch:
   push:
-    branches:
-      - develop
+    branches: [ "develop" ]
+  pull_request:
+    branches: [ "develop" ]
+
+permissions:
+  contents: read
 
 jobs:
   build:
-    name: Build and Push Docker Image
     runs-on: ubuntu-latest
-    outputs:
-      docker_image_tag: ${{ steps.set_tag.outputs.docker_image_tag }}
-
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+      - uses: actions/checkout@v3
 
-      - name: Set up JDK 17
+      - name: Install JDK 17
         uses: actions/setup-java@v3
         with:
           java-version: '17'
           distribution: 'temurin'
 
-      - name: Make secret files
-        run: |
-          mkdir -p ./src/main/resources
-          echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml
-
       - name: Build with Gradle
         run: |
           chmod +x ./gradlew
-          ./gradlew clean build
-
-      - name: Set Docker image tag (by date)
-        id: set_tag
-        run: echo "docker_image_tag=$(date +'%Y%m%d-%H%M')" >> $GITHUB_OUTPUT
+          ./gradlew clean bootJar -x test
 
       - name: Login to DockerHub
-        uses: docker/login-action@v3
+        uses: docker/login-action@v1
         with:
-          username: ${{ secrets.DOCKER_HUB_USERNAME }}
-          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      - name: Build and Push Docker image
-        run: |
-          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/wayble:${{ steps.set_tag.outputs.docker_image_tag }} .
-          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/wayble:${{ steps.set_tag.outputs.docker_image_tag }}
+      - name: Build Docker
+        run: docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/live_server .
+
+      - name: Push Docker
+        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/live_server:latest
 
   deploy:
-    name: Deploy to EC2
-    runs-on: ubuntu-latest
     needs: build
-
+    runs-on: ubuntu-latest
     steps:
-      - name: SSH to EC2 and deploy
-        uses: appleboy/ssh-action@v1.2.0
+      - name: Set target IP
+        run: |
+          STATUS=$(curl -o /dev/null -w "%{http_code}" "http://${{ secrets.WAYBLE_SERVER_IP }}/env")
+          if [ "$STATUS" = "200" ]; then
+            CURRENT_UPSTREAM=$(curl -s "http://${{ secrets.WAYBLE_SERVER_IP }}/env")
+          else
+            CURRENT_UPSTREAM=green
+          fi
+
+          echo "CURRENT_UPSTREAM=$CURRENT_UPSTREAM" >> $GITHUB_ENV
+
+          if [ "$CURRENT_UPSTREAM" = "blue" ]; then
+            echo "CURRENT_PORT=8080" >> $GITHUB_ENV
+            echo "STOPPED_PORT=8081" >> $GITHUB_ENV
+            echo "TARGET_UPSTREAM=green" >> $GITHUB_ENV
+            echo "TARGET_CONTAINER=green" >> $GITHUB_ENV
+            echo "CURRENT_CONTAINER=blue" >> $GITHUB_ENV
+          elif [ "$CURRENT_UPSTREAM" = "green" ]; then
+            echo "CURRENT_PORT=8081" >> $GITHUB_ENV
+            echo "STOPPED_PORT=8080" >> $GITHUB_ENV
+            echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV
+            echo "TARGET_CONTAINER=blue" >> $GITHUB_ENV
+            echo "CURRENT_CONTAINER=green" >> $GITHUB_ENV
+          else
+            echo "error: invalid CURRENT_UPSTREAM"
+            exit 1
+          fi
+
+
+      - name: Docker compose
+        uses: appleboy/ssh-action@master
         with:
-          host: ${{ secrets.EC2_HOST }}
-          username: ${{ secrets.EC2_USER }}
+          username: ubuntu
+          host: ${{ secrets.WAYBLE_SERVER_IP }}
           key: ${{ secrets.EC2_SSH_KEY }}
+          script_stop: true
           script: |
-            cd wayble-spring
-            git pull
-            echo "TAG=${{ needs.build.outputs.docker_image_tag }}" > .env
-            sudo docker-compose stop wayble-app
-            sudo docker-compose rm -f wayble-app
-            sudo docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/wayble:$TAG || true
-            sudo docker-compose pull wayble-app
-            sudo docker-compose up -d wayble-app --no-deps
+            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/live_server:latest
+            sudo docker-compose -f docker-compose-${{env.TARGET_UPSTREAM}}.yml up -d
+
+      - name: Check deploy server URL
+        uses: jtalk/url-health-check-action@v3
+        with:
+          url: http://${{ secrets.WAYBLE_SERVER_IP }}:${{env.STOPPED_PORT}}/env
+          max-attempts: 3
+          retry-delay: 10s
+
+      - name: Change nginx upstream
+        uses: appleboy/ssh-action@master
+        with:
+          username: ubuntu
+          host: ${{ secrets.WAYBLE_SERVER_IP }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script_stop: true
+          script: |
+            sudo docker exec -i nginxserver bash -c 'echo "set \$service_url ${{ env.TARGET_UPSTREAM }};" > /etc/nginx/service-env.inc && nginx -s reload'
 
 
-
+      - name: Stop current server
+        uses: appleboy/ssh-action@master
+        with:
+          username: ubuntu
+          host: ${{ secrets.WAYBLE_SERVER_IP }}
+          key: ${{ secrets.EC2_SSH_KEY }}
+          script_stop: true
+          script: |
+            sudo docker stop ${{env.CURRENT_CONTAINER}}
+            sudo docker rm ${{env.CURRENT_CONTAINER}}
 
 # name: CD - DEVELOP
 
